<?php

namespace AppBundle\Repository;

/**
 * PhpreposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhpreposRepository extends \Doctrine\ORM\EntityRepository
{
}
